global:
  scrape_interval:     1s
  evaluation_interval: 30s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['api:8087']
  - job_name: traefik
    static_configs:
      - targets: ['traefik:9010']