version: '3.1'

services:

  api:
    image: b01:latest
    #build:
    #  context: ./
    #  dockerfile: ./Dockerfile
    ports:
      - 9005:9005
      - 8087:8087
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: db01
    ports:
      - 5433:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8085:8080

  prometheus:
    image: prom/prometheus
    ports:
      - 9007:9090
    volumes:
      - "./prom:/etc/prometheus"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - api

  traefik:
    image: traefik
    ports:
      # HTTP 
      - 9008:80
      # The Web UI (enabled by --api.insecure=true)
      - 9009:8080
      # Prometheus metrics exposer
      - 9010:9010
    volumes:
      - ./traefik/traefik.toml:/etc/traefik/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock
  
  grafana:
    image: grafana/grafana:9.0.4
    ports:
      - 9011:3000
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource