version: '3.1'

services:

#  api:
#    build:
#      context: ./
#      dockerfile: ./Dockerfile
#    ports:
#      - 9005:9005

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: db01
    ports:
      - 5433:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8085:8080